# Unique project key (required)
sonar.projectKey=mzmiguelwd_univalle-desarrollo-II-neo-sira
sonar.organization=mzmiguelwd

# Source code to be analyzed
sonar.sources=backend/src,frontend/src

# Where to find unit tests
sonar.tests=backend/tests,frontend/src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx

# Coverage report paths
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info

# Exclusions (Do not analyze dependencies or configurations)
sonar.exclusions=**/node_modules/**,**/*.config.js,**/dist/**